In [43]:
import $ivy.`me.shadaj::scalapy-core:0.5.2`
import $ivy.`org.wvlet.airframe::airframe-json:22.10.3`
import $ivy.`org.wvlet.airframe::airframe-codec:22.10.3`
import me.shadaj.scalapy.py
import me.shadaj.scalapy.py.SeqConverters  
import wvlet.airframe.json.JSON
import wvlet.airframe.codec.MessageCodec
 val hc = py.module("homcloud.interface")  
 val pv = py.module("homcloud.paraview_interface") 
 val go = py.module("plotly.graph_objects")  
val alt = py.module("altair")
val pd = py.module("pandas")
val np = py.module("numpy")
val data = py.module("vega_datasets").data
val vega = py.module("vega").VegaLite

import $ivy.$                              

import $ivy.$                                          

import $ivy.$                                           

import me.shadaj.scalapy.py

import me.shadaj.scalapy.py.SeqConverters  

import wvlet.airframe.json.JSON

import wvlet.airframe.codec.MessageCodec
 
hc: py.Module = <module 'homcloud.interface' from '/mnt/disks/sdb/home2/tetsu.sato/.local/lib/python3.10/site-packages/homcloud/interface/__init__.py'>
pv: py.Module = <module 'homcloud.paraview_interface' from '/mnt/disks/sdb/home2/tetsu.sato/.local/lib/python3.10/site-packages/homcloud/paraview_interface.py'>
go: py.Module = <module 'plotly.graph_objects' from '/mnt/disks/sdb/home2/tetsu.sato/.local/lib/python3.10/site-packages/plotly/graph_objects/__init__.py'>
alt: py.Module = <module 'altair' from '/mnt/disks/sdb/home2/tetsu.sato/.local/lib/python3.10/site-packages/altair/__init__.py'>
pd: py.Module = <module 'pandas' from '/mnt/disks/sdb/home2/tetsu.sato/.local/lib/python3.10

In [43]:
VegaLite(
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "data": {
    "values": [
      {"a": "C", "b": 2},
      {"a": "C", "b": 7},
      {"a": "C", "b": 4},
      {"a": "D", "b": 1},
      {"a": "D", "b": 2},
      {"a": "D", "b": 6},
      {"a": "E", "b": 8},
      {"a": "E", "b": 4},
      {"a": "E", "b": 7}
    ]
  },
  "mark": "point",
  "encoding": {
    "x": {"field": "a", "type": "nominal"},
    "y": {"field": "b", "type": "quantitative"}
  }
}
)

(console):3:63 expected "}"
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
                                                              ^

: 

In [36]:
alt.renderers.enable("mimetype")
alt.renderers.enable("html")
val cars = data.cars

val html = alt.Chart(cars).mark_point().encode(
    x="Horsepower",
    y="Miles_per_Gallon",
    color="Origin",
)

res35_0: py.Dynamic = RendererRegistry.enable('mimetype')
res35_1: py.Dynamic = RendererRegistry.enable('html')
cars: py.Dynamic = <vega_datasets.core.Cars object at 0x7f6f80942530>
html: py.Dynamic = alt.Chart(...)

In [37]:
alt.Chart(cars).

res36: py.Dynamic = alt.Chart(...)

In [ ]:
# Compute x^2 + y^2 across a 2D grid
x, y = np.meshgrid(range(-5, 5), range(-5, 5))
z = x ** 2 + y ** 2

# Convert this grid to columnar data expected by Altair
source = pd.DataFrame({'x': x.ravel(),
                     'y': y.ravel(),
                     'z': z.ravel()})

alt.Chart(source).mark_rect().encode(
    x='x:O',
    y='y:O',
    color='z:Q'
)

In [3]:
 val np = py.module("numpy")    
val pointcloud = np.loadtxt("../pointcloud.txt")   
 val pdlist = hc.PDList("pointcloud.pdgm")  
val pd1 = pdlist.dth_diagram(1)   
 val birth = pd1.births.as[Seq[Double]]  
 val deaths = pd1.deaths.as[Seq[Double]]  
 val fig = go.Figure(   
      data=(go.Scatter(x=pd1.births, y=pd1.deaths, mode="markers")) 
     )

np: py.Module = <module 'numpy' from '/mnt/disks/sdb/home2/tetsu.sato/.local/lib/python3.10/site-packages/numpy/__init__.py'>
pointcloud: py.Dynamic = [[0.60787872 0.81431219 0.89241913]
 [0.07278738 0.29077335 0.92234073]
 [0.2998963  0.98017103 0.24894357]
 ...
 [0.12760227 0.67915379 0.3646432 ]
 [0.2663476  0.00483151 0.02911984]
 [0.17887994 0.42554668 0.62179437]]
pdlist: py.Dynamic = PDList(path=pointcloud.pdgm)
pd1: py.Dynamic = PD(path=pointcloud.pdgm, d=1)
birth: Seq[Double] = List(
  0.001409063487607722,
  0.0013959100007524036,
  0.001341164405649675,
  0.0017156724858769022,
  0.0016472884816911221,
  0.0014063684167515429,
  0.0016762824981449774,
  0.001725052160391382,
  0.0014965876375920505,
  0.0016034145257796614,
  0.0017249363765330231,
  0.0016850147234634912,
  0.0015376921916033022,
  0.0015990215413647963,
  0.0018329799669325772,
  0.001604524049711499,
  0.0017469678875586822,
  0.0019437539356499088,
  0.0017807214933227373,
  0.001830990133768673,
  0.001

In [3]:
fig.show()

: 

In [ ]:
fig

In [19]:
fig.show

res18: py.Dynamic = <bound method BaseFigure.show of Figure({
    'data': [{'mode': 'markers',
              'type': 'scatter',
              'x': array([0.00140906, 0.00139591, 0.00134116, ..., 0.01572219, 0.01709659,
                          0.01871588]),
              'y': array([0.0015926 , 0.00164399, 0.00170775, ..., 0.0157662 , 0.01717465,
                          0.01880101])}],
    'layout': {'template': '...'}
})>

In [4]:
 val pio = py.module("plotly.io")  

pio: py.Module = <module 'plotly.io' from '/mnt/disks/sdb/home2/tetsu.sato/.local/lib/python3.10/site-packages/plotly/io/__init__.py'>

In [5]:
pio.renderers

res4: py.Dynamic = Renderers configuration
-----------------------
    Default renderer: 'browser'
    Available renderers:
        ['plotly_mimetype', 'jupyterlab', 'nteract', 'vscode',
         'notebook', 'notebook_connected', 'kaggle', 'azure', 'colab',
         'cocalc', 'databricks', 'json', 'png', 'jpeg', 'jpg', 'svg',
         'pdf', 'browser', 'firefox', 'chrome', 'chromium', 'iframe',
         'iframe_connected', 'sphinx_gallery', 'sphinx_gallery_png']


In [ ]:
alt.

In [10]:
case class ImageObject(mime: String, javascript: String)
val codec = MessageCodec.of[ImageObject]
val s = fig.show(renderer="plotly_mimetype")
//codec.unpackJson(s)
//s.as[String]
s

{'application/vnd.plotly.v1+json': {'data': [{'mode': 'markers', 'x': [0.001409063487607722, 0.0013959100007524036, 0.001341164405649675, 0.0017156724858769022, 0.0016472884816911221, 0.0014063684167515429, 0.0016762824981449774, 0.001725052160391382, 0.0014965876375920505, 0.0016034145257796614, 0.0017249363765330231, 0.0016850147234634912, 0.0015376921916033022, 0.0015990215413647963, 0.0018329799669325772, 0.001604524049711499, 0.0017469678875586822, 0.0019437539356499088, 0.0017807214933227373, 0.001830990133768673, 0.0018917922263412509, 0.0017703461031329543, 0.0016897454102886083, 0.0019011820191888202, 0.0020021939465587712, 0.001781904882774749, 0.0016009179333060976, 0.0018572406542189104, 0.00202734948737833, 0.0016325463080227671, 0.001988279483942052, 0.0018387291145157548, 0.0016905203805986236, 0.001794737473104296, 0.0021430803255346694, 0.0018583142215894135, 0.0019202167708024655, 0.002104976379742134, 0.002163672487671922, 0.0018955247739485905, 0.0017455654342100526

defined class ImageObject
codec: MessageCodec[ImageObject] = ObjectCodec(
  surface = ImageObject,
  paramCodec = Vector(
    wvlet.airframe.codec.PrimitiveCodec$StringCodec$@412f6f6c,
    wvlet.airframe.codec.PrimitiveCodec$StringCodec$@412f6f6c
  )
)
s: py.Dynamic = None
res9_3: py.Dynamic = None

In [8]:
s

cmd8.sc:1: not found: value s
val res8 = s
           ^Compilation Failed

: 

In [8]:
fig.show(renderer="notebook").

res7: py.Dynamic = None

In [17]:
fig.show(renderer="svg")

res16: py.Dynamic = None

In [2]:
fig.show(renderer="png")

cmd2.sc:1: not found: value fig
val res2 = fig.show(renderer="png")
           ^cmd2.sc:1: not found: value renderer
val res2 = fig.show(renderer="png")
                    ^Compilation Failed

: 

In [19]:
fig.show(renderer="json")

res18: py.Dynamic = None

In [11]:
fig.show(renderer="iframe")

{'text/html': '<iframe\n    scrolling="no"\n    width="100%"\n    height="545px"\n    src="iframe_figures/figure_0.html"\n    frameborder="0"\n    allowfullscreen\n></iframe>\n'}


res10: py.Dynamic = None

In [2]:
fig.show(renderer="plotly_mimetype")

cmd2.sc:1: not found: value fig
val res2 = fig.show(renderer="plotly_mimetype")
           ^cmd2.sc:1: not found: value renderer
val res2 = fig.show(renderer="plotly_mimetype")
                    ^Compilation Failed

: 

In [29]:
val plt = py.module("matplotlib.pyplot")
val mpimg = py.module("matplotlib.image")

plt: py.Module = <module 'matplotlib.pyplot' from '/mnt/disks/sdb/home2/tetsu.sato/.local/lib/python3.10/site-packages/matplotlib/pyplot.py'>
mpimg: py.Module = <module 'matplotlib.image' from '/mnt/disks/sdb/home2/tetsu.sato/.local/lib/python3.10/site-packages/matplotlib/image.py'>

In [28]:
plt.plot(Array(1.0, 2.0).toPythonProxy, Array(2.0, 3.0).toPythonProxy).

res27: py.Dynamic = [<matplotlib.lines.Line2D object at 0x7faad43a14b0>]

In [9]:
%matplotlib inline

cmd9.sc:1: not found: value %
val res9 = %matplotlib inline
           ^cmd9.sc:1: not found: value inline
val res9 = %matplotlib inline
                       ^Compilation Failed

: 

In [38]:
Javascript(
"""var script = document.createElement('script'); script.type = 'text/javascript'; script.src = '//cdn.jsdelivr.net/npm/vega@5'; document.head.appendChild(script); var script = document.createElement('script'); script.type = 'text/javascript'; script.src = '//cdn.jsdelivr.net/npm/vega-embed@6'; document.head.appendChild(script); """)
import $ivy.`com.lihaoyi::ujson:1.3.12`
import $ivy.`com.lihaoyi::requests:0.6.5`
val spec = ujson.read(requests.get("https://vega.github.io/vega/examples/bar-chart.vg.json").text)

spec("data")(0)("values") = ujson.Arr(
  ujson.Obj("category" -> "Epic", "amount" -> 50),
  ujson.Obj("category" -> "amounts", "amount" -> 100)
)
Javascript(s""" vegaEmbed(element, $spec).then(function(result) { }).catch(console.error) """)

import $ivy.$                          

import $ivy.$                            

spec: ujson.Value.Value = Obj(
  value = LinkedHashMap(
    "$schema" -> Str(value = "https://vega.github.io/schema/vega/v5.json"),
    "description" -> Str(
      value = "A basic bar chart example, with value labels shown upon mouse hover."
    ),
    "width" -> Num(value = 400.0),
    "height" -> Num(value = 200.0),
    "padding" -> Num(value = 5.0),
    "data" -> Arr(
      value = ArrayBuffer(
        Obj(
          value = LinkedHashMap(
            "name" -> Str(value = "table"),
            "values" -> Arr(
              value = ArrayBuffer(
                Obj(
                  value = LinkedHashMap(
                    "category" -> Str(value = "Epic"),
                    "amount" -> Num(value = 50.0)
                  )
                ),
                Obj(
                  value = LinkedHashMap(
                    "category" -> Str(value = "amounts"),
                    "amount" -> Nu

In [39]:
val image = py.module("PIL.Image")
val is = py.module("PIL.ImageShow")

image: py.Module = <module 'PIL.Image' from '/mnt/disks/sdb/home2/tetsu.sato/.local/lib/python3.10/site-packages/PIL/Image.py'>
is: py.Module = <module 'PIL.ImageShow' from '/mnt/disks/sdb/home2/tetsu.sato/.local/lib/python3.10/site-packages/PIL/ImageShow.py'>

In [40]:
is.show(image.open("pointcloud.png"))

res39: py.Dynamic = True

In [24]:


import me.shadaj.scalapy.interpreter.CPythonInterpreter
val sys = py.module("sys")
CPythonInterpreter.execManyLines(
  """class OutputRedirector:
    |  def __init__(self, write_fn, flush_fn):
    |    self.write_fn = write_fn
    |    self.flush_fn = flush_fn
    |  def write(self, text):
    |    self.write_fn(text)
    |  def flush(self):
    |    self.flush_fn()""".stripMargin
)

val stdoutRedirector = py.Dynamic.global.OutputRedirector(
  py.Any.from((text: String) => {
    System.out.print(text)
    py.None
  }),
  py.Any.from(() => {
    System.out.flush()
    py.None
  })
)

sys.stdout = stdoutRedirector

val stderrRedirector = py.Dynamic.global.OutputRedirector(
  py.Any.from((text: String) => {
    System.err.print(text)
    py.None
  }),
  py.Any.from(() => {
    System.err.flush()
    py.None
  })
)

sys.stderr = stderrRedirector



import me.shadaj.scalapy.interpreter.CPythonInterpreter

sys: py.Module = <module 'sys' (built-in)>
stdoutRedirector: py.Dynamic = <OutputRedirector object at 0x7f6f80913a30>
stderrRedirector: py.Dynamic = <OutputRedirector object at 0x7f6f809134f0>